# Generated by Django 4.1.13 on 2024-01-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_english', models.CharField(max_length=100, verbose_name='English Name')),
                ('name_hebrew', models.CharField(max_length=100, verbose_name='שם בעברית')),
                ('name_french', models.CharField(max_length=100, verbose_name='French Name')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
