# Generated by Django 4.1.13 on 2024-01-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word_english', models.CharField(max_length=50, verbose_name='English Word')),
                ('word_hebrew', models.CharField(max_length=50, verbose_name='מילה בעברית')),
                ('word_french', models.CharField(max_length=50, verbose_name='French Word')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='base.lesson')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
    ]
