# Generated by Django 4.1.13 on 2024-02-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_key',
            field=models.CharField(default='to_fill', max_length=50, verbose_name='word to search'),
            preserve_default=False,
        ),
    ]
